version: '3.8'

services:
  # FastAPI Backend Service
  api:
    build: .
    container_name: green-skills-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./models:/app/models
      - ./Datasets:/app/Datasets
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Streamlit UI Service
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: green-skills-ui
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://api:8000
    depends_on:
      - api
    restart: unless-stopped

networks:
  default:
    name: green-skills-network

